### ISSUE TITLE
TableView Appears under navigationBar after releasing.

### ISSUE THREAD

**Issue by Stan92** [micazeve/MAGearRefreshControl#2]
Hi,
Using your demo everything is ok.
Using my app, when I start dragging down my tableview, it moves under the navigation bar (something like 20px goes under the navBar).
Any idea how to fix this?
Thanks

---

Ok, I've found the solution... sorry for the post.
I unticked the Extend Edges (Under Top bars and Bottom Bars).

**Comment by micazeve** [comment]
Hi,
Sorry for the delay, I wasn't available for a few days ! 

I'm glad you found the issue anyway ;)
